backend:
  name: github
  repo: TheLabCollective/vector
  branch: main
media_folder: "/assets/images/uploads" # Media files will be stored in the repo under assets/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads
collections:
  - name: "email"
    label: "Email"
    folder: "/content/emails"
    create: true
    slug: "{{slug}}" # title.md
    fields:
      - {label: "Title (filename)", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Subject", name: "subject", widget: "string"}
      - {label: "Triggered by choice list", name: "triggered_by", widget: "list"}
      - {label: "Choices", name: "choices", widget: "list"}
      - {label: "Economic change", name: "scoreChangeEconomic", widget: "list"}
      - {label: "Harm change", name: "scoreChangeHarm", widget: "list"}
      - {label: "Success change", name: "scoreChangeSuccess", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "message"
    label: "Message"
    folder: "/content/messages"
    create: true
    slug: "{{slug}}" # title.md
    fields:
      - {label: "Title (filename)", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Triggered by choice list", name: "triggered_by", widget: "list"}
      - {label: "Player message", name: "playerMessage", widget: "string"}
      - {label: "Choices", name: "choices", widget: "list"}
      - {label: "Economic change", name: "scoreChangeEconomic", widget: "list"}
      - {label: "Harm change", name: "scoreChangeHarm", widget: "list"}
      - {label: "Success change", name: "scoreChangeSuccess", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
